//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Resources/Input/ControllerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControllerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControllerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControllerInput"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""363770b4-a921-4481-9ef7-a1ae445f5ede"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""12bb9be2-4207-483c-a434-4ee4ed2183ca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9ca78a33-a3b9-45f0-baaa-52900c82bf8b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ModifierKeyLeft"",
                    ""type"": ""Button"",
                    ""id"": ""64a7908a-4ce3-4ccf-88d6-34d8510b2abf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ModifierKeyRight"",
                    ""type"": ""Button"",
                    ""id"": ""2c195e8a-94ef-47ea-9526-1a27efca151a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionSprint"",
                    ""type"": ""Button"",
                    ""id"": ""e4c8e510-7205-4409-ab38-8ba4898807ae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionSurecast"",
                    ""type"": ""Button"",
                    ""id"": ""962f3348-0ba4-4442-a834-36d786bf7df9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""4d260cdb-f348-410e-804d-6e41ecffceca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""83ff938c-d0ba-459c-9aaf-f8e225bb8ca8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settings"",
                    ""type"": ""Button"",
                    ""id"": ""949718cc-1bc6-49e7-817a-e1dbe2cdcd66"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""5ab672c0-03a7-43c4-92fa-e3aa72c2fa7c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGapcloser1"",
                    ""type"": ""Button"",
                    ""id"": ""44dca6fc-fee2-4c05-8388-8fcb42917f9f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Play"",
                    ""type"": ""Button"",
                    ""id"": ""012beec1-4c0f-4520-9385-c19833d6e7a3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""d97d7339-6c0b-4805-8b26-7d864f37433c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""668bea2c-6b1b-4b9f-9c4b-f0b22ad3f3ba"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""bc2103b9-86d9-406c-b9ec-12da62dab06d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Button"",
                    ""id"": ""f47a18ae-9a5c-47a2-bd2d-8b51a7d93bce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGapcloser2"",
                    ""type"": ""Button"",
                    ""id"": ""a70ef2cd-c0f0-48fc-8c82-2d22c5a2291f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGapcloser3"",
                    ""type"": ""Button"",
                    ""id"": ""508fb1c6-a865-41b5-91ad-d4b3941e73cb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGapcloser4"",
                    ""type"": ""Button"",
                    ""id"": ""184a0746-87a3-44e1-bb02-072b788a8ae4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGapcloser5"",
                    ""type"": ""Button"",
                    ""id"": ""06ece9af-5770-4090-8a94-2adcb46d24da"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGapcloser6"",
                    ""type"": ""Button"",
                    ""id"": ""b82b1948-94c8-468e-97eb-ea75bee6c3f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGapcloser7"",
                    ""type"": ""Button"",
                    ""id"": ""5051ca77-aca8-4d96-9a4c-de681670f349"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionSwiftcast"",
                    ""type"": ""Button"",
                    ""id"": ""da3a1cbb-9d22-4df5-8e6d-cea152296575"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionMightyGuard"",
                    ""type"": ""Button"",
                    ""id"": ""599a5651-902e-4278-9d99-f7c92f489a6a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionWhiteWind"",
                    ""type"": ""Button"",
                    ""id"": ""d43c34bd-8e4b-464d-a134-32d9fafdc52d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionDiamondback"",
                    ""type"": ""Button"",
                    ""id"": ""50622402-6be8-4046-a713-b69123673f47"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionFrogLegs"",
                    ""type"": ""Button"",
                    ""id"": ""a34f950f-8e38-4f8c-bef3-b84f2d6071e1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionSonicBoom"",
                    ""type"": ""Button"",
                    ""id"": ""6f18d5b1-c709-4494-b24c-35a79fb2449b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGobskin"",
                    ""type"": ""Button"",
                    ""id"": ""934239c1-770a-4f8b-b845-a424edd52958"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionDevour"",
                    ""type"": ""Button"",
                    ""id"": ""1befab4b-ac50-40f0-97ae-eb63cb5d5f0c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""680a71a5-4b4d-41da-9bdd-d55735b06e0a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3397ade0-3b41-43d1-be4b-c334dcd5aa19"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0639d210-de8c-491a-b5e3-666c67160228"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ModifierKeyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6606db5-f07f-4d28-8999-c7f33906174c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ModifierKeyRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbd061d1-1cc7-4f34-a290-dca06dd8ee7e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2390661b-807c-418e-a0b5-58d9de70ce37"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2ee7f9f-bade-4896-8ab8-0c86163cbb44"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionSurecast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19e44741-0f1c-4ebd-877b-ec2135203dff"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f0880c3-c828-4714-9175-fc54aac633de"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d27642f-5238-4fc5-b071-05ef11f56889"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Settings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47be00b3-3da6-45fb-862c-e872dba2767b"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a54403d-34ff-40d0-90e8-a314aace91d8"",
                    ""path"": ""<DualShockGamepad>/touchpadButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37e1935d-64ac-4135-b440-e2074975e450"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c63fbfff-3f3e-493d-a1fd-62d9bc4403ba"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionGapcloser1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7603af06-3d03-4fbf-9ee0-8bf052df546d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Play"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0251ad8b-cb87-4116-89b6-0ac911276702"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcd4157e-8973-4e43-9a3f-be00e81a5e07"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6c66315-5ed1-482c-be95-429799650643"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e0c6516-3774-41b3-aa5b-f7428413dfdf"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b3a36ed-625d-44ee-b221-6e227e999ffa"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionGapcloser2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c7189b6-a684-413b-a253-311e522b846e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionGapcloser3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71f9c674-ae86-4ef9-81eb-eb50511d49d6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionGapcloser4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21dbde64-71ee-4c7a-954b-59ea3f57663f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionGapcloser5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a98ac21b-c820-42e5-8946-0d18a14ae6f5"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionGapcloser6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5ebf445-ffa9-4407-981d-6b3a72ab8d3b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionGapcloser7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a700c41-a9f3-4639-8328-8d8ba39e04f2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionSwiftcast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcc58077-b62b-406f-8544-1619630a926e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionMightyGuard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b1f271f-139a-403a-9394-216192720426"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionWhiteWind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65171436-fb3f-4ee2-a2da-dc0d46532c33"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionDiamondback"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fd65899-40d3-47e6-a723-f5eac139cd88"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionFrogLegs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""813b6d93-59b1-48e1-a2c9-9ecc629c4816"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionSonicBoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af2a1505-dcf9-4a1f-993f-e7f9d6fb45a6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionGobskin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09f79619-c1ca-452c-9539-9e45e2c7064e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ActionDevour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_Movement = m_Main.FindAction("Movement", throwIfNotFound: true);
        m_Main_Camera = m_Main.FindAction("Camera", throwIfNotFound: true);
        m_Main_ModifierKeyLeft = m_Main.FindAction("ModifierKeyLeft", throwIfNotFound: true);
        m_Main_ModifierKeyRight = m_Main.FindAction("ModifierKeyRight", throwIfNotFound: true);
        m_Main_ActionSprint = m_Main.FindAction("ActionSprint", throwIfNotFound: true);
        m_Main_ActionSurecast = m_Main.FindAction("ActionSurecast", throwIfNotFound: true);
        m_Main_Cancel = m_Main.FindAction("Cancel", throwIfNotFound: true);
        m_Main_Submit = m_Main.FindAction("Submit", throwIfNotFound: true);
        m_Main_Settings = m_Main.FindAction("Settings", throwIfNotFound: true);
        m_Main_Pause = m_Main.FindAction("Pause", throwIfNotFound: true);
        m_Main_ActionGapcloser1 = m_Main.FindAction("ActionGapcloser1", throwIfNotFound: true);
        m_Main_Play = m_Main.FindAction("Play", throwIfNotFound: true);
        m_Main_Reload = m_Main.FindAction("Reload", throwIfNotFound: true);
        m_Main_Reset = m_Main.FindAction("Reset", throwIfNotFound: true);
        m_Main_Jump = m_Main.FindAction("Jump", throwIfNotFound: true);
        m_Main_CameraZoom = m_Main.FindAction("CameraZoom", throwIfNotFound: true);
        m_Main_ActionGapcloser2 = m_Main.FindAction("ActionGapcloser2", throwIfNotFound: true);
        m_Main_ActionGapcloser3 = m_Main.FindAction("ActionGapcloser3", throwIfNotFound: true);
        m_Main_ActionGapcloser4 = m_Main.FindAction("ActionGapcloser4", throwIfNotFound: true);
        m_Main_ActionGapcloser5 = m_Main.FindAction("ActionGapcloser5", throwIfNotFound: true);
        m_Main_ActionGapcloser6 = m_Main.FindAction("ActionGapcloser6", throwIfNotFound: true);
        m_Main_ActionGapcloser7 = m_Main.FindAction("ActionGapcloser7", throwIfNotFound: true);
        m_Main_ActionSwiftcast = m_Main.FindAction("ActionSwiftcast", throwIfNotFound: true);
        m_Main_ActionMightyGuard = m_Main.FindAction("ActionMightyGuard", throwIfNotFound: true);
        m_Main_ActionWhiteWind = m_Main.FindAction("ActionWhiteWind", throwIfNotFound: true);
        m_Main_ActionDiamondback = m_Main.FindAction("ActionDiamondback", throwIfNotFound: true);
        m_Main_ActionFrogLegs = m_Main.FindAction("ActionFrogLegs", throwIfNotFound: true);
        m_Main_ActionSonicBoom = m_Main.FindAction("ActionSonicBoom", throwIfNotFound: true);
        m_Main_ActionGobskin = m_Main.FindAction("ActionGobskin", throwIfNotFound: true);
        m_Main_ActionDevour = m_Main.FindAction("ActionDevour", throwIfNotFound: true);
    }

    ~@ControllerInput()
    {
        UnityEngine.Debug.Assert(!m_Main.enabled, "This will cause a leak and performance issues, ControllerInput.Main.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private List<IMainActions> m_MainActionsCallbackInterfaces = new List<IMainActions>();
    private readonly InputAction m_Main_Movement;
    private readonly InputAction m_Main_Camera;
    private readonly InputAction m_Main_ModifierKeyLeft;
    private readonly InputAction m_Main_ModifierKeyRight;
    private readonly InputAction m_Main_ActionSprint;
    private readonly InputAction m_Main_ActionSurecast;
    private readonly InputAction m_Main_Cancel;
    private readonly InputAction m_Main_Submit;
    private readonly InputAction m_Main_Settings;
    private readonly InputAction m_Main_Pause;
    private readonly InputAction m_Main_ActionGapcloser1;
    private readonly InputAction m_Main_Play;
    private readonly InputAction m_Main_Reload;
    private readonly InputAction m_Main_Reset;
    private readonly InputAction m_Main_Jump;
    private readonly InputAction m_Main_CameraZoom;
    private readonly InputAction m_Main_ActionGapcloser2;
    private readonly InputAction m_Main_ActionGapcloser3;
    private readonly InputAction m_Main_ActionGapcloser4;
    private readonly InputAction m_Main_ActionGapcloser5;
    private readonly InputAction m_Main_ActionGapcloser6;
    private readonly InputAction m_Main_ActionGapcloser7;
    private readonly InputAction m_Main_ActionSwiftcast;
    private readonly InputAction m_Main_ActionMightyGuard;
    private readonly InputAction m_Main_ActionWhiteWind;
    private readonly InputAction m_Main_ActionDiamondback;
    private readonly InputAction m_Main_ActionFrogLegs;
    private readonly InputAction m_Main_ActionSonicBoom;
    private readonly InputAction m_Main_ActionGobskin;
    private readonly InputAction m_Main_ActionDevour;
    public struct MainActions
    {
        private @ControllerInput m_Wrapper;
        public MainActions(@ControllerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Main_Movement;
        public InputAction @Camera => m_Wrapper.m_Main_Camera;
        public InputAction @ModifierKeyLeft => m_Wrapper.m_Main_ModifierKeyLeft;
        public InputAction @ModifierKeyRight => m_Wrapper.m_Main_ModifierKeyRight;
        public InputAction @ActionSprint => m_Wrapper.m_Main_ActionSprint;
        public InputAction @ActionSurecast => m_Wrapper.m_Main_ActionSurecast;
        public InputAction @Cancel => m_Wrapper.m_Main_Cancel;
        public InputAction @Submit => m_Wrapper.m_Main_Submit;
        public InputAction @Settings => m_Wrapper.m_Main_Settings;
        public InputAction @Pause => m_Wrapper.m_Main_Pause;
        public InputAction @ActionGapcloser1 => m_Wrapper.m_Main_ActionGapcloser1;
        public InputAction @Play => m_Wrapper.m_Main_Play;
        public InputAction @Reload => m_Wrapper.m_Main_Reload;
        public InputAction @Reset => m_Wrapper.m_Main_Reset;
        public InputAction @Jump => m_Wrapper.m_Main_Jump;
        public InputAction @CameraZoom => m_Wrapper.m_Main_CameraZoom;
        public InputAction @ActionGapcloser2 => m_Wrapper.m_Main_ActionGapcloser2;
        public InputAction @ActionGapcloser3 => m_Wrapper.m_Main_ActionGapcloser3;
        public InputAction @ActionGapcloser4 => m_Wrapper.m_Main_ActionGapcloser4;
        public InputAction @ActionGapcloser5 => m_Wrapper.m_Main_ActionGapcloser5;
        public InputAction @ActionGapcloser6 => m_Wrapper.m_Main_ActionGapcloser6;
        public InputAction @ActionGapcloser7 => m_Wrapper.m_Main_ActionGapcloser7;
        public InputAction @ActionSwiftcast => m_Wrapper.m_Main_ActionSwiftcast;
        public InputAction @ActionMightyGuard => m_Wrapper.m_Main_ActionMightyGuard;
        public InputAction @ActionWhiteWind => m_Wrapper.m_Main_ActionWhiteWind;
        public InputAction @ActionDiamondback => m_Wrapper.m_Main_ActionDiamondback;
        public InputAction @ActionFrogLegs => m_Wrapper.m_Main_ActionFrogLegs;
        public InputAction @ActionSonicBoom => m_Wrapper.m_Main_ActionSonicBoom;
        public InputAction @ActionGobskin => m_Wrapper.m_Main_ActionGobskin;
        public InputAction @ActionDevour => m_Wrapper.m_Main_ActionDevour;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void AddCallbacks(IMainActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @ModifierKeyLeft.started += instance.OnModifierKeyLeft;
            @ModifierKeyLeft.performed += instance.OnModifierKeyLeft;
            @ModifierKeyLeft.canceled += instance.OnModifierKeyLeft;
            @ModifierKeyRight.started += instance.OnModifierKeyRight;
            @ModifierKeyRight.performed += instance.OnModifierKeyRight;
            @ModifierKeyRight.canceled += instance.OnModifierKeyRight;
            @ActionSprint.started += instance.OnActionSprint;
            @ActionSprint.performed += instance.OnActionSprint;
            @ActionSprint.canceled += instance.OnActionSprint;
            @ActionSurecast.started += instance.OnActionSurecast;
            @ActionSurecast.performed += instance.OnActionSurecast;
            @ActionSurecast.canceled += instance.OnActionSurecast;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Settings.started += instance.OnSettings;
            @Settings.performed += instance.OnSettings;
            @Settings.canceled += instance.OnSettings;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @ActionGapcloser1.started += instance.OnActionGapcloser1;
            @ActionGapcloser1.performed += instance.OnActionGapcloser1;
            @ActionGapcloser1.canceled += instance.OnActionGapcloser1;
            @Play.started += instance.OnPlay;
            @Play.performed += instance.OnPlay;
            @Play.canceled += instance.OnPlay;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @CameraZoom.started += instance.OnCameraZoom;
            @CameraZoom.performed += instance.OnCameraZoom;
            @CameraZoom.canceled += instance.OnCameraZoom;
            @ActionGapcloser2.started += instance.OnActionGapcloser2;
            @ActionGapcloser2.performed += instance.OnActionGapcloser2;
            @ActionGapcloser2.canceled += instance.OnActionGapcloser2;
            @ActionGapcloser3.started += instance.OnActionGapcloser3;
            @ActionGapcloser3.performed += instance.OnActionGapcloser3;
            @ActionGapcloser3.canceled += instance.OnActionGapcloser3;
            @ActionGapcloser4.started += instance.OnActionGapcloser4;
            @ActionGapcloser4.performed += instance.OnActionGapcloser4;
            @ActionGapcloser4.canceled += instance.OnActionGapcloser4;
            @ActionGapcloser5.started += instance.OnActionGapcloser5;
            @ActionGapcloser5.performed += instance.OnActionGapcloser5;
            @ActionGapcloser5.canceled += instance.OnActionGapcloser5;
            @ActionGapcloser6.started += instance.OnActionGapcloser6;
            @ActionGapcloser6.performed += instance.OnActionGapcloser6;
            @ActionGapcloser6.canceled += instance.OnActionGapcloser6;
            @ActionGapcloser7.started += instance.OnActionGapcloser7;
            @ActionGapcloser7.performed += instance.OnActionGapcloser7;
            @ActionGapcloser7.canceled += instance.OnActionGapcloser7;
            @ActionSwiftcast.started += instance.OnActionSwiftcast;
            @ActionSwiftcast.performed += instance.OnActionSwiftcast;
            @ActionSwiftcast.canceled += instance.OnActionSwiftcast;
            @ActionMightyGuard.started += instance.OnActionMightyGuard;
            @ActionMightyGuard.performed += instance.OnActionMightyGuard;
            @ActionMightyGuard.canceled += instance.OnActionMightyGuard;
            @ActionWhiteWind.started += instance.OnActionWhiteWind;
            @ActionWhiteWind.performed += instance.OnActionWhiteWind;
            @ActionWhiteWind.canceled += instance.OnActionWhiteWind;
            @ActionDiamondback.started += instance.OnActionDiamondback;
            @ActionDiamondback.performed += instance.OnActionDiamondback;
            @ActionDiamondback.canceled += instance.OnActionDiamondback;
            @ActionFrogLegs.started += instance.OnActionFrogLegs;
            @ActionFrogLegs.performed += instance.OnActionFrogLegs;
            @ActionFrogLegs.canceled += instance.OnActionFrogLegs;
            @ActionSonicBoom.started += instance.OnActionSonicBoom;
            @ActionSonicBoom.performed += instance.OnActionSonicBoom;
            @ActionSonicBoom.canceled += instance.OnActionSonicBoom;
            @ActionGobskin.started += instance.OnActionGobskin;
            @ActionGobskin.performed += instance.OnActionGobskin;
            @ActionGobskin.canceled += instance.OnActionGobskin;
            @ActionDevour.started += instance.OnActionDevour;
            @ActionDevour.performed += instance.OnActionDevour;
            @ActionDevour.canceled += instance.OnActionDevour;
        }

        private void UnregisterCallbacks(IMainActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @ModifierKeyLeft.started -= instance.OnModifierKeyLeft;
            @ModifierKeyLeft.performed -= instance.OnModifierKeyLeft;
            @ModifierKeyLeft.canceled -= instance.OnModifierKeyLeft;
            @ModifierKeyRight.started -= instance.OnModifierKeyRight;
            @ModifierKeyRight.performed -= instance.OnModifierKeyRight;
            @ModifierKeyRight.canceled -= instance.OnModifierKeyRight;
            @ActionSprint.started -= instance.OnActionSprint;
            @ActionSprint.performed -= instance.OnActionSprint;
            @ActionSprint.canceled -= instance.OnActionSprint;
            @ActionSurecast.started -= instance.OnActionSurecast;
            @ActionSurecast.performed -= instance.OnActionSurecast;
            @ActionSurecast.canceled -= instance.OnActionSurecast;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Settings.started -= instance.OnSettings;
            @Settings.performed -= instance.OnSettings;
            @Settings.canceled -= instance.OnSettings;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @ActionGapcloser1.started -= instance.OnActionGapcloser1;
            @ActionGapcloser1.performed -= instance.OnActionGapcloser1;
            @ActionGapcloser1.canceled -= instance.OnActionGapcloser1;
            @Play.started -= instance.OnPlay;
            @Play.performed -= instance.OnPlay;
            @Play.canceled -= instance.OnPlay;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @CameraZoom.started -= instance.OnCameraZoom;
            @CameraZoom.performed -= instance.OnCameraZoom;
            @CameraZoom.canceled -= instance.OnCameraZoom;
            @ActionGapcloser2.started -= instance.OnActionGapcloser2;
            @ActionGapcloser2.performed -= instance.OnActionGapcloser2;
            @ActionGapcloser2.canceled -= instance.OnActionGapcloser2;
            @ActionGapcloser3.started -= instance.OnActionGapcloser3;
            @ActionGapcloser3.performed -= instance.OnActionGapcloser3;
            @ActionGapcloser3.canceled -= instance.OnActionGapcloser3;
            @ActionGapcloser4.started -= instance.OnActionGapcloser4;
            @ActionGapcloser4.performed -= instance.OnActionGapcloser4;
            @ActionGapcloser4.canceled -= instance.OnActionGapcloser4;
            @ActionGapcloser5.started -= instance.OnActionGapcloser5;
            @ActionGapcloser5.performed -= instance.OnActionGapcloser5;
            @ActionGapcloser5.canceled -= instance.OnActionGapcloser5;
            @ActionGapcloser6.started -= instance.OnActionGapcloser6;
            @ActionGapcloser6.performed -= instance.OnActionGapcloser6;
            @ActionGapcloser6.canceled -= instance.OnActionGapcloser6;
            @ActionGapcloser7.started -= instance.OnActionGapcloser7;
            @ActionGapcloser7.performed -= instance.OnActionGapcloser7;
            @ActionGapcloser7.canceled -= instance.OnActionGapcloser7;
            @ActionSwiftcast.started -= instance.OnActionSwiftcast;
            @ActionSwiftcast.performed -= instance.OnActionSwiftcast;
            @ActionSwiftcast.canceled -= instance.OnActionSwiftcast;
            @ActionMightyGuard.started -= instance.OnActionMightyGuard;
            @ActionMightyGuard.performed -= instance.OnActionMightyGuard;
            @ActionMightyGuard.canceled -= instance.OnActionMightyGuard;
            @ActionWhiteWind.started -= instance.OnActionWhiteWind;
            @ActionWhiteWind.performed -= instance.OnActionWhiteWind;
            @ActionWhiteWind.canceled -= instance.OnActionWhiteWind;
            @ActionDiamondback.started -= instance.OnActionDiamondback;
            @ActionDiamondback.performed -= instance.OnActionDiamondback;
            @ActionDiamondback.canceled -= instance.OnActionDiamondback;
            @ActionFrogLegs.started -= instance.OnActionFrogLegs;
            @ActionFrogLegs.performed -= instance.OnActionFrogLegs;
            @ActionFrogLegs.canceled -= instance.OnActionFrogLegs;
            @ActionSonicBoom.started -= instance.OnActionSonicBoom;
            @ActionSonicBoom.performed -= instance.OnActionSonicBoom;
            @ActionSonicBoom.canceled -= instance.OnActionSonicBoom;
            @ActionGobskin.started -= instance.OnActionGobskin;
            @ActionGobskin.performed -= instance.OnActionGobskin;
            @ActionGobskin.canceled -= instance.OnActionGobskin;
            @ActionDevour.started -= instance.OnActionDevour;
            @ActionDevour.performed -= instance.OnActionDevour;
            @ActionDevour.canceled -= instance.OnActionDevour;
        }

        public void RemoveCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainActions @Main => new MainActions(this);
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IMainActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnModifierKeyLeft(InputAction.CallbackContext context);
        void OnModifierKeyRight(InputAction.CallbackContext context);
        void OnActionSprint(InputAction.CallbackContext context);
        void OnActionSurecast(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnSettings(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnActionGapcloser1(InputAction.CallbackContext context);
        void OnPlay(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
        void OnActionGapcloser2(InputAction.CallbackContext context);
        void OnActionGapcloser3(InputAction.CallbackContext context);
        void OnActionGapcloser4(InputAction.CallbackContext context);
        void OnActionGapcloser5(InputAction.CallbackContext context);
        void OnActionGapcloser6(InputAction.CallbackContext context);
        void OnActionGapcloser7(InputAction.CallbackContext context);
        void OnActionSwiftcast(InputAction.CallbackContext context);
        void OnActionMightyGuard(InputAction.CallbackContext context);
        void OnActionWhiteWind(InputAction.CallbackContext context);
        void OnActionDiamondback(InputAction.CallbackContext context);
        void OnActionFrogLegs(InputAction.CallbackContext context);
        void OnActionSonicBoom(InputAction.CallbackContext context);
        void OnActionGobskin(InputAction.CallbackContext context);
        void OnActionDevour(InputAction.CallbackContext context);
    }
}
